### ISSUE TITLE
Implement heating levels

### ISSUE THREAD

**Issue by couto** [miguelcnf/heat#1]
It's not always full blown cold winter during the year ❄️ , sometimes is just Autumn 🍂 , it would be nice to be able to convert my laptop into a smaller/less powerful heater, you know... just something good enough to keep my ☕️  warm.

Also it would be nice to just have a portable fan during summer 🍹 .

**Comment by reistiago** [comment]
Perhaps spinning up half the cores would be better for Autumn

**Comment by miguelcnf** [comment]
You guys are weirdos
